### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by LucasPanology** [humanmade/cf-to-tf#10]
Running the command against a real-life CloudFormation Template.
`cf-to-tf --stack - config < /home/Username/bastion.cfn | json2hcl | cf-to-tf clean-hcl | terraform fmt - | tee /home/Username/Bastions.tf.json`

and get the error 
`unable to parse JSON: 1:9: illegal char`

I shorten the first command to 
`cf-to-tf --stack - config < /home/Username/bastion.cfn`

and get the error 
`TypeError: Cannot read property '0' of undefined
    at getStack.then.result (/usr/local/lib/node_modules/@humanmade/cf-to-tf/index.js:47:54)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)`

**Comment by ntman4real** [comment]
I have the same issue.  How did you resolve?

**Comment by LucasGood** [comment]
Can't reproduce; previous environment is gone. Sorry.
