### ISSUE TITLE
Cloudformation template support?

### ISSUE THREAD

**Issue by dlobue** [humanmade/cf-to-tf#4]
Hey, great tool! Works perfectly for a cloudformation stack that has already been deployed! Any plans on adding support for converting cloudformation templates to tf format?

AWS has some very nice CF templates for production-ready clusters for quite a few apps: https://aws.amazon.com/quickstart/

The one for nomad, for example, sets up VPC, a bastion, consul, etc: https://aws.amazon.com/quickstart/architecture/nomad/

Currently learning terraform (and the rest of the hashicorp stack), I'd like to avoid having to add CF to that list.

Thanks!

**Comment by nathanielks** [comment]
Hi @dlobue!

My sincerest apologies for the delay in this response! My email was misbehaving all summer, so I missed a lot of notifications.

To your question! No, there aren't any plans on adding this functionality. I _had_ considered that, but it wasn't something I had the bandwidth or interest in maintaining. It would require a lot of mapping CloudFormation resource names and parameters to Terraform, and with there being so many resources, it was just too much work I didn't feel like doing 😅 . 

That said, a lot of parameters _do_ map nearly 1:1, so you could feasibly look at a CloudFormation stack and copy most of it to Terraform and converting the parameters to lowercase snake_case. Easier said than done, of course 😛

**Comment by nathanielks** [comment]
For those interested, there is https://github.com/dtan4/terraforming, which can create associated terraform resources and state!
